version: '2'

services:

    db:
        image: mariadb:latest
        volumes:
            - ./data/db:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    wordpress:
        depends_on:
            - db
        image: chepurko/wordpress-redis
        volumes:
            - ./data/blog:/var/www/html
            - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
#            - ./wp-config.php:/var/www/html/wp-config.php
        restart: always
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress

    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./config/site.conf:/etc/nginx/conf.d/default.conf
            - ./data/blog:/var/www/html
        restart: always
          
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        volumes:
            - ./data/redis:/data
        restart: always

#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin:latest
#        ports:
#            - "8888:80"
#        volumes:
#            - ./data/phpmyadmin:/sessions
#        restart: always
#        environment:
#            PMA_HOST: db
#            PMA_USER: wordpress
#            PMA_PASSWORD: wordpress
#            PHP_UPLOAD_MAX_FILESIZE: 1G
#            PHP_MAX_INPUT_VARS: 1G
